# Build stage
FROM node:lts-alpine as build

WORKDIR /app


COPY app/client/package*.json ./
RUN npm install


COPY app/client/ .


RUN npm run build

# Production stage
FROM nginx:stable-alpine as production


COPY --from=build /app/dist /usr/share/nginx/html


COPY app/nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"] 