FROM python:3.12-slim

WORKDIR /app


RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*


COPY pyproject.toml poetry.lock ./
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --without dev


COPY settings.py ./
COPY app/ ./app/
COPY udata.json ./udata.json


COPY docker/init-db.sh ./init-db.sh
RUN chmod +x ./init-db.sh

EXPOSE 5000


CMD ["./init-db.sh"] 